### PR TITLE
Increase min iOS version from 7 to 9

### PR DESCRIPTION
**Pull request by hamishmack**

### CODE REVIEW

**Comment by ryantrinkle** [comment]
Should this be configurable?

**Comment by hamishmack** [comment]
> Should this be configurable?

I think it would be nice if it did not prevent user from providing there own minimum.  Currently it seems to override whatever min version is passed to the linker.

**Comment by ryantrinkle** [comment]
Maybe there could be a way of configuring it at the nix level - i.e. some argument that gets passed through to this code.

**Comment by hamishmack** [comment]
Would that still require a complete nix rebuild (or download) of the ios-cross tool chain and everything that depends on it to change the min version placed on an executable?   If one executable required min ver 10.1 and one required min ver 10.2 would shared dependencies have to be built twice?

**Comment by ryantrinkle** [comment]
If this change did, it would.  That's definitely a problem, although it still seems preferable to having it completely hard-coded.

**Pull request merged**
